[package]
name = "CedraOracle"
version = "1.0.0"
upgrade_policy = "compatible"

[dependencies]
CedraFramework = { git = "https://github.com/cedra-labs/cedra-network", subdir = "cedra-move/framework/cedra-framework/", rev = "6e846b37919bd1c8e773d4248ae221546550596f" }
MoveStdlib = { git = "https://github.com/cedra-labs/cedra-network", subdir = "cedra-move/framework/move-stdlib/", rev = "6e846b37919bd1c8e773d4248ae221546550596f" }
CedraStdlib = { git = "https://github.com/cedra-labs/cedra-network", subdir = "cedra-move/framework/cedra-stdlib/", rev = "6e846b37919bd1c8e773d4248ae221546550596f" }
CedraToken = { git = "https://github.com/cedra-labs/cedra-network", subdir = "cedra-move/framework/cedra-token/", rev = "6e846b37919bd1c8e773d4248ae221546550596f" }
CedraMessage = { git = "https://github.com/cedra-labs/cedra-messaging-protocol.git", subdir = "cedra_message", rev = "8e5cd0cbad5e942d9742b905f7c312980e57287b" }
Deployer = { git = "https://github.com/cedra-labs/cedra-package-deployer.git", rev = "c866d40d139ce4a35f66ca93986be6c69cce31e3" }

[addresses]
# oracle = "_"
# deployer = "_"
# cedra_message = "_"

# [dev-addresses]
oracle = "0x970327406aba31ce0a2c5801e85d2caecb599c448e819a4aca1999eae4b5e860"
deployer = "c745ffa4f97fa9739fae0cb173996f70bb8e4b0310fa781ccca2f7dc13f7db06"
cedra_message = "0x57322093852c70567c85f724df12994591d589082e921ca16a43f80cb9755446"
